<?php
$p='image_hotspots'; $eyebrow=get_field("{$p}_eyebrow"); $title=get_field("{$p}_title"); $content=get_field("{$p}_content"); $image=get_field("{$p}_image"); $hotspots=get_field("{$p}_hotspots")?:[]; $settings=get_field("{$p}_section_settings"); $sectionId=inkwell_component_id($block??[],'image-hotspots');
?>
<section id="<?php echo esc_attr($sectionId); ?>" class="image-hotspots px-6 <?php echo esc_attr(inkwell_component_section_classes($settings,$p)); ?>" data-hotspots>
 <div class="mx-auto grid items-center gap-12 lg:grid-cols-[.65fr_1.35fr] <?php echo esc_attr(inkwell_component_container_class($settings,$p)); ?>">
  <div><?php if($eyebrow){?><p class="mb-4 text-xs font-semibold uppercase tracking-[.14em] opacity-60"><?php echo esc_html($eyebrow);?></p><?php }?><?php if($title){?><h2 class="text-[clamp(32px,4vw,48px)] font-semibold leading-tight tracking-[-.035em]"><?php echo esc_html($title);?></h2><?php }?><?php if($content){?><div class="mt-5 leading-7 opacity-75"><?php echo wp_kses_post($content);?></div><?php }?>
   <div class="mt-7 space-y-2"><?php foreach($hotspots as $i=>$spot){?><button type="button" class="hotspot-trigger flex w-full items-center gap-3 rounded px-2 py-2 text-left text-sm <?php echo $i===0?'is-active text-[#0867f2]':'opacity-75';?>" data-hotspot-index="<?php echo esc_attr($i);?>" aria-controls="<?php echo esc_attr("$sectionId-hotspot-$i");?>" aria-pressed="<?php echo $i===0?'true':'false';?>"><span class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#eaf2ff] text-xs text-[#0867f2]"><?php echo esc_html($i+1);?></span><?php echo esc_html($spot["{$p}_hotspot_title"]??'');?></button><?php }?></div>
   <div class="mt-4 min-h-[72px]"><?php foreach($hotspots as $i=>$spot){?><div id="<?php echo esc_attr("$sectionId-hotspot-$i");?>" class="hotspot-detail text-sm leading-6 opacity-70" data-hotspot-detail="<?php echo esc_attr($i);?>"<?php if($i!==0)echo' hidden';?>><?php echo wp_kses_post($spot["{$p}_hotspot_description"]??'');?></div><?php }?></div>
  </div>
  <div class="relative aspect-[16/10] overflow-hidden bg-[#e9edf3]"><?php echo inkwell_component_image($image,'full','h-full w-full object-cover');?><?php foreach($hotspots as $i=>$spot){$x=max(0,min(100,(float)($spot["{$p}_hotspot_x"]??50)));$y=max(0,min(100,(float)($spot["{$p}_hotspot_y"]??50)));?><button type="button" class="hotspot-marker absolute flex h-9 w-9 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-2 border-white bg-[#0867f2] text-sm font-semibold text-white shadow-lg focus:outline-none focus:ring-4 focus:ring-[#0867f2]/30" style="left:<?php echo esc_attr($x);?>%;top:<?php echo esc_attr($y);?>%" data-hotspot-index="<?php echo esc_attr($i);?>" aria-controls="<?php echo esc_attr("$sectionId-hotspot-$i");?>" aria-label="<?php echo esc_attr(($i+1).'. '.($spot["{$p}_hotspot_title"]??'Hotspot'));?>" aria-pressed="<?php echo $i===0?'true':'false';?>"><?php echo esc_html($i+1);?></button><?php }?></div>
 </div>
</section>
